// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/callback": {
    params: {};
  };
  "/qa-runner": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/callback" | "/qa-runner" | "/*";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./callback/page.jsx": {
    id: "callback/page";
    page: "/callback";
  };
  "./qa-runner/page.jsx": {
    id: "qa-runner/page";
    page: "/qa-runner";
  };
  "./__create/not-found.tsx": {
    id: "__create/not-found";
    page: "/" | "/*";
  };
};