-- AlterTable
ALTER TABLE "public"."tracks" ALTER COLUMN "duration_ms" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "popularity" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "key" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "mode" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "time_signature" SET DATA TYPE DECIMAL(65,30);
